// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCo5Y8adtOU6y-XYQYmK073FcSZmEHaKys',
    appId: '1:628374339120:web:a8b362693ab6c596fef7f5',
    messagingSenderId: '628374339120',
    projectId: 'nsc-competition',
    authDomain: 'nsc-competition.firebaseapp.com',
    storageBucket: 'nsc-competition.appspot.com',
    measurementId: 'G-ZRSH7K05XP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwyHwAUgYWGOz5FI4d8Di7VnxrWpGJnEE',
    appId: '1:628374339120:android:d2311427da758a5afef7f5',
    messagingSenderId: '628374339120',
    projectId: 'nsc-competition',
    storageBucket: 'nsc-competition.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdZmkq6pa7oBdevd1SW5sZa1iTv3tC84U',
    appId: '1:628374339120:ios:aa72ff295b6c9735fef7f5',
    messagingSenderId: '628374339120',
    projectId: 'nsc-competition',
    storageBucket: 'nsc-competition.appspot.com',
    androidClientId: '628374339120-mb12b2enutf74rvqkji8c037n4el44u8.apps.googleusercontent.com',
    iosClientId: '628374339120-qp5e5pffujv2na187k82ueh63hpl84p8.apps.googleusercontent.com',
    iosBundleId: 'com.example.nscWhatidanSecurity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdZmkq6pa7oBdevd1SW5sZa1iTv3tC84U',
    appId: '1:628374339120:ios:aa72ff295b6c9735fef7f5',
    messagingSenderId: '628374339120',
    projectId: 'nsc-competition',
    storageBucket: 'nsc-competition.appspot.com',
    androidClientId: '628374339120-mb12b2enutf74rvqkji8c037n4el44u8.apps.googleusercontent.com',
    iosClientId: '628374339120-qp5e5pffujv2na187k82ueh63hpl84p8.apps.googleusercontent.com',
    iosBundleId: 'com.example.nscWhatidanSecurity',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCo5Y8adtOU6y-XYQYmK073FcSZmEHaKys',
    appId: '1:628374339120:web:0de8c4e389d54813fef7f5',
    messagingSenderId: '628374339120',
    projectId: 'nsc-competition',
    authDomain: 'nsc-competition.firebaseapp.com',
    storageBucket: 'nsc-competition.appspot.com',
    measurementId: 'G-NX7WHV5LG6',
  );

}